__all__: list[str]

class Error(Exception):
    """Base class for every pywire-defined exception."""

class ProtocolError(Error):
    """Wire-protocol-level violation."""

class AuthError(Error):
    """Authentication-related error (including SASL/SCRAM/OAuth)."""

class UnsupportedProtocolVersion(ProtocolError): ...
class InvalidCancelRequest(ProtocolError): ...
class InvalidMessageType(ProtocolError): ...
class MessageTooLarge(ProtocolError): ...
class InvalidTargetType(ProtocolError): ...
class InvalidTransactionStatus(ProtocolError): ...
class InvalidSSLRequestMessage(ProtocolError): ...
class InvalidGssEncRequestMessage(ProtocolError): ...
class InvalidStartupMessage(ProtocolError): ...
class InvalidAuthenticationMessageCode(ProtocolError): ...
class InvalidSecretKey(ProtocolError): ...
class NotReadyForQuery(ProtocolError): ...
class InvalidOptionValue(ProtocolError): ...
class FailedToCoercePasswordMessage(AuthError): ...
class InvalidSASLState(AuthError): ...
class UnsupportedSASLAuthMethod(AuthError): ...
class InvalidScramMessage(AuthError): ...
class InvalidPassword(AuthError): ...
class UnsupportedCertificateSignatureAlgorithm(AuthError): ...
class UserNameRequired(AuthError): ...
class InvalidOauthMessage(AuthError): ...
class OAuthAuthenticationFailed(AuthError): ...
class OAuthValidationError(AuthError): ...
class OauthAuthzIdError(AuthError): ...
class PortalNotFound(Error): ...
class PortalNotStarted(Error): ...
class StatementNotFound(Error): ...
class ParameterIndexOutOfBound(Error): ...
class InvalidRustTypeForParameter(Error): ...
class FailedToParseParameter(Error): ...
class QueryCanceled(Error): ...
class ApiError(Error): ...
class UserError(Error): ...

class ErrorInfo:
    """PostgreSQL error/notice field set.

    Mirrors `pgwire::error::ErrorInfo`. Field names follow the
    PostgreSQL protocol error-fields reference one-to-one.
    """

    severity: str
    code: str
    message: str
    detail: str | None
    hint: str | None
    position: str | None
    internal_position: str | None
    internal_query: str | None
    where_context: str | None
    file_name: str | None
    line: int | None
    routine: str | None
    severity_nonlocalized: str | None
    schema: str | None
    table: str | None
    column: str | None
    datatype: str | None
    constraint: str | None

    def __init__(
        self,
        severity: str,
        code: str,
        message: str,
        *,
        detail: str | None = None,
        hint: str | None = None,
        position: str | None = None,
        internal_position: str | None = None,
        internal_query: str | None = None,
        where_context: str | None = None,
        file_name: str | None = None,
        line: int | None = None,
        routine: str | None = None,
        severity_nonlocalized: str | None = None,
        schema: str | None = None,
        table: str | None = None,
        column: str | None = None,
        datatype: str | None = None,
        constraint: str | None = None,
    ) -> None: ...
    def is_fatal(self) -> bool:
        """True when `severity == 'FATAL'`."""
